### ISSUE TITLE
Better sorting UI

### ISSUE THREAD

**Issue by felixcodes** [vega/voyager#625] opened 2017-08-17 21:01 UTC
Create a popup-component for sorting data. Tableau's implementation:

![image](https://user-images.githubusercontent.com/17525561/29433549-7371a9e2-8354-11e7-8530-38a417df7025.png)

**Comment by kanitw** [comment] 2017-08-18 02:36
I think we can have a similar UI as a Pop-up component 

For "sort by", we can have by alphabetic or by field for now.

**Comment by kanitw** [comment] 2018-05-16 00:08
Duplicate of https://github.com/vega/voyager/issues/761

**Closed by kanitw** 2018-05-16 00:08 UTC
