### ISSUE TITLE
Warnings thrown when run yarn test:ui

### ISSUE THREAD

**Issue by starry97** [vega/voyager#688] opened 2017-09-01 23:31 UTC
UI tests throw the following warning
```
  console.error lib-test/lib-voyager.test.ui.tsx.js:1
      Warning: It looks like you're using a minified copy of the development build of React. When deploying React
 apps to production, make sure to use the production build which skips development warnings and is faster. See ht
tps://fb.me/react-minification for more details.
```

**Comment by kanitw** [comment] 2017-09-06 00:30
Duplicate of https://github.com/vega/voyager/issues/702

**Closed by kanitw** 2017-09-06 00:30 UTC
